### ISSUE TITLE
登陆页面不是只有邮箱才能进来么，添加成员没有做邮箱校验

### ISSUE THREAD

**Issue by Anda-iOS** [FeatureProbe/feature-probe-ui#39]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/28703327/197490979-319c6ad5-096e-40cd-81ba-1c9e327e1cdd.png">

**Comment by yuying-Alice** [comment]
FeatureProbe的开源版本是使用账号密码登录（不限制账号形式，邮箱、手机号等都可以），线上io环境为了方便用户快速体验，提供了免密码登录，只需要输入邮箱即可（线上io环境完整的保留了开源版本的所有能力）

**Comment by yuying-Alice** [comment]
账号管理的邮箱校验，我们加一下

**Comment by frankzhaopeng** [comment]
Reference #44
